apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: fortio
        image: fortio/fortio
        command: ["fortio"]
        args:
          - load
          - -c
          - "16"
          - -qps
          - "200" 
          - -t
          - "10m"
          - http://nginx-target.kube-system.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-target
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-target
  template:
    metadata:
      labels:
        app: nginx-target
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-target
  namespace: kube-system
spec:
  ports:
  - port: 80
  selector:
    app: nginx-target